const fallbackNews=[
{id:"seed-1",title:"いわき七夕まつり、きょう最終日　平商店街を彩る夏の風物詩",summary:"平商店街で開催中の「いわき七夕まつり」は8月8日が最終日。市の案内では10時から20時30分まで開催予定で、同日夕方にはいわきおどりも行われます。",category:"イベント",area:"平",publishedAt:"2026-08-08T08:00:00+09:00",source:"いわき市",sourceUrl:"https://www.city.iwaki.lg.jp/www/genre/1000100000345/index.html"},
{id:"seed-2",title:"いわきおどり、きょう17時から　駅前大通りが熱気に包まれる",summary:"いわきの夏を代表する「いわきおどり」が8月8日、いわき駅前大通りで開催予定。",category:"イベント",area:"平",publishedAt:"2026-08-08T07:50:00+09:00",source:"いわき市",sourceUrl:"https://www.city.iwaki.lg.jp/www/genre/1000100000345/index.html"},
{id:"seed-3",title:"いわき駅前大通りで無料公衆Wi-Fi　8月3日から提供開始",summary:"いわき駅前大通りで無料公衆Wi-Fiの提供が始まりました。",category:"暮らし",area:"平",publishedAt:"2026-08-03T09:00:00+09:00",source:"いわき民報",sourceUrl:"https://iwaki-minpo.co.jp/news/2026/07/313779/"},
{id:"seed-4",title:"福島県知事選　いわき市の新人が立候補を表明",summary:"任期満了に伴う福島県知事選挙をめぐる動きです。",category:"市政",area:"全市",publishedAt:"2026-08-05T12:00:00+09:00",source:"福島テレビ",sourceUrl:"https://www.fukushima-tv.co.jp/"},
{id:"seed-5",title:"市内37公民館、後期の市民講座を案内",summary:"いわき市は、市内37公民館で実施する市民講座を公開しました。",category:"教育・子育て",area:"全市",publishedAt:"2026-07-31T10:00:00+09:00",source:"いわき市",sourceUrl:"https://www.city.iwaki.lg.jp/"},
{id:"seed-7",title:"勿来・國玉神社の「風鈴参道」　8月16日まで",summary:"勿来町窪田の國玉神社では、風鈴とこけ玉で彩る「風鈴参道」を開催中です。",category:"イベント",area:"勿来",publishedAt:"2026-07-28T11:00:00+09:00",source:"いわき民報",sourceUrl:"https://iwaki-minpo.co.jp/"},
{id:"seed-8",title:"いわき市の海水浴場、8月16日まで開設",summary:"いわき市内の海水浴場は夏季開設中です。",category:"暮らし",area:"四倉",publishedAt:"2026-07-20T09:30:00+09:00",source:"いわき民報",sourceUrl:"https://iwaki-minpo.co.jp/"},
{id:"seed-9",title:"いわきFC応援キャンペーン　ブックエースで実施",summary:"地域ぐるみでクラブを後押しする企画が展開されます。",category:"スポーツ",area:"全市",publishedAt:"2026-08-07T12:00:00+09:00",source:"いわきFC",sourceUrl:"https://iwakifc.com/"}
];
const regionAreas=["平","小名浜","勿来","常磐","内郷","四倉","遠野","小川","好間","三和","田人","川前","久之浜・大久"];
let news=fallbackNews,generatedAt=null,sourceCount=null;
const state={category:"すべて",area:"すべて",query:"",sort:"new"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:'#'}catch{return '#'}};
const fmt=iso=>new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const timeAgo=iso=>{const m=Math.max(0,Math.floor((Date.now()-new Date(iso))/60000));if(m<60)return `${m}分前`;const h=Math.floor(m/60);if(h<24)return `${h}時間前`;return `${Math.floor(h/24)}日前`};
function sortedNews(){return [...news].sort((a,b)=>(state.sort==='old'?1:-1)*(new Date(a.publishedAt)-new Date(b.publishedAt)))}
function filteredNews(){return sortedNews().filter(n=>(state.category==='すべて'||n.category===state.category)&&(state.area==='すべて'||n.area===state.area||n.area==='全市')&&(!state.query||`${n.title} ${n.summary||''} ${n.category} ${n.area} ${n.source}`.toLowerCase().includes(state.query.toLowerCase())))}
function renderTopFive(){const items=[...news].sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,5);$('#topFive').innerHTML=items.map((n,i)=>`<button class="top-five-item" data-id="${esc(n.id)}" type="button"><span class="top-five-num">${i+1}</span><span class="top-five-copy"><strong>${esc(n.title)}</strong><small>${esc(n.source)}</small></span><time>${timeAgo(n.publishedAt)}</time></button>`).join('')}
function cardMarkup(n){return `<article class="news-card"><div class="news-thumb" data-category="${esc(n.category)}"><span class="thumb-badge">${esc(n.category)}</span></div><div class="news-card-body"><h3>${esc(n.title)}</h3><p>${esc(n.summary||'')}</p><div class="news-card-footer"><div class="source"><b>${esc(n.area)}</b>${esc(n.source)}　${timeAgo(n.publishedAt)}</div><button class="read-button" data-id="${esc(n.id)}" type="button">→</button></div></div></article>`}
function renderNews(){const items=filteredNews();$('#newsGrid').innerHTML=items.map(cardMarkup).join('');$('#resultCount').textContent=`${items.length}件`;$('#emptyState').hidden=items.length!==0;updateRegionStates()}
function renderMeta(){if($('#sourceCount'))$('#sourceCount').textContent=sourceCount?`${sourceCount}媒体`:'複数媒体';if($('#lastUpdated'))$('#lastUpdated').textContent=generatedAt?`最終更新 ${fmt(generatedAt)}`:'デモデータ表示中'}
function regionCount(area){return news.filter(n=>n.area===area).length}
function regionButtonHtml(area){return `<button class="region-button" data-area="${esc(area)}" type="button" aria-label="${esc(area)}のニュースを見る"><span class="region-button-name">${esc(area)}</span><span class="region-button-count">${regionCount(area)}件</span></button>`}
function initRegionNav(){const nav=$('#regionNav');if(!nav)return;nav.innerHTML=`<button class="region-button region-all" data-area="すべて" type="button"><span class="region-button-name">市内全域</span><span class="region-button-count">${news.length}件</span></button>`+regionAreas.map(regionButtonHtml).join('');nav.addEventListener('click',e=>{const btn=e.target.closest('.region-button');if(btn)selectArea(btn.dataset.area)})}
function refreshRegionButtons(){const nav=$('#regionNav');if(!nav)return;nav.querySelectorAll('.region-button').forEach(btn=>{const area=btn.dataset.area;btn.classList.toggle('active',state.area===area);const count=area==='すべて'?news.length:regionCount(area);const countEl=btn.querySelector('.region-button-count');if(countEl)countEl.textContent=`${count}件`})}
function updateRegionStates(){refreshRegionButtons()}
function syncFilters(){if($('#categoryFilter'))$('#categoryFilter').value=state.category;if($('#areaFilter'))$('#areaFilter').value=state.area;if($('#searchInput'))$('#searchInput').value=state.query;if($('#headerSearchInput'))$('#headerSearchInput').value=state.query;$$('.nav-chip').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category));$('#allFilter')?.classList.toggle('active',state.category==='すべて'&&state.area==='すべて'&&!state.query);renderNews()}
function selectArea(area){state.area=area;syncFilters();$('#latestTitle')?.scrollIntoView({behavior:'smooth',block:'start'})}
function selectCategory(cat){state.category=cat;syncFilters();$('#latestTitle')?.scrollIntoView({behavior:'smooth',block:'start'})}
function openArticle(id){const n=news.find(x=>String(x.id)===String(id));if(!n)return;$('#dialogContent').innerHTML=`<div class="dialog-kicker"><span>${esc(n.category)}</span><time>${fmt(n.publishedAt)}</time></div><h2>${esc(n.title)}</h2><p class="dialog-summary">${esc(n.summary||'')}</p><div class="dialog-meta"><b>地域：</b>${esc(n.area)}<br><b>出典：</b>${esc(n.source)}</div><a class="source-button" href="${safeUrl(n.sourceUrl)}" target="_blank" rel="noopener noreferrer">元情報を確認する ↗</a><p class="dialog-note">いわきNOWは出典を明示し、元記事へのリンクを優先します。</p>`;$('#articleDialog').showModal()}
async function loadNews(){try{const r=await fetch('./data/news.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);const p=await r.json();if(Array.isArray(p.news)&&p.news.length){news=p.news;generatedAt=p.generatedAt||null;sourceCount=p.sourceCount||(Array.isArray(p.sources)?p.sources.length:null)}}catch(e){console.info('内蔵デモデータを表示します',e)}renderTopFive();renderNews();renderMeta();refreshRegionButtons()}
function bindEvents(){document.addEventListener('click',e=>{const id=e.target.closest('[data-id]')?.dataset.id;if(id)openArticle(id)});$$('.nav-chip').forEach(b=>b.addEventListener('click',()=>selectCategory(b.dataset.category)));$$('#mobileNav [data-category]').forEach(b=>b.addEventListener('click',()=>{selectCategory(b.dataset.category);$('#mobileNav').hidden=true}));$('#categoryFilter').addEventListener('change',e=>{state.category=e.target.value;syncFilters()});$('#areaFilter').addEventListener('change',e=>{state.area=e.target.value;syncFilters()});$('#sortFilter').addEventListener('change',e=>{state.sort=e.target.value;renderNews()});for(const id of ['searchInput','headerSearchInput'])$("#"+id).addEventListener('input',e=>{state.query=e.target.value;syncFilters()});$('#clearFilters').addEventListener('click',()=>{Object.assign(state,{category:'すべて',area:'すべて',query:'',sort:'new'});$('#sortFilter').value='new';syncFilters();});$('#allFilter').addEventListener('click',()=>{Object.assign(state,{category:'すべて',area:'すべて',query:''});syncFilters()});$('#resetRegion').addEventListener('click',()=>{state.area='すべて';syncFilters();});$('#showAllNews').addEventListener('click',()=>$('#latestTitle').scrollIntoView({behavior:'smooth'}));$('#closeDialog').addEventListener('click',()=>$('#articleDialog').close());$('#menuButton').addEventListener('click',()=>{const nav=$('#mobileNav');nav.hidden=!nav.hidden;$('#menuButton').setAttribute('aria-expanded',String(!nav.hidden))});$('#articleDialog').addEventListener('click',e=>{if(e.target===$('#articleDialog'))$('#articleDialog').close()})}
bindEvents();initRegionNav();loadNews();
